---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
