---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-pushgateway
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  endpoints:
  - port: http
